### ISSUE TITLE
Publish a specification for the vocabularies on Github Pages

### ISSUE THREAD

**Issue by melaasar** [opencaesar/vocabularies#4]
## User Story
As a vocabulary developer, I would like to publish a spec for the vocabulary on GitHub Pages, to make it easy to consume by vocabulary stakeholders.

## Detailed Description
Use the oml2bikeshed tool to publish the spec in Bikeshed format

## Acceptance Criteria
- [ ] The spec docs are accessible from the URL: https://opencaesar.github.io/vocabularies

## Tasks
- [ ] Setup the repo to have a gh-pages branch
- [ ] Create a Travis CI script that checkouts the oml2bikeshed repo to run the tool

**Comment by melaasar** [comment]
All vocabulary repos, including core-vocabularies now have gh=pages branch: http://www.opencaesar.io/core-vocabularies/
